/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormConsultaEstoqueGeral;
import br.mackenzie.simacr.interfaces.IEntidadeItemEstoque;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class FormConsultaEstoqueGeral extends javax.swing.JFrame {
    
    private IControllerFormConsultaEstoqueGeral controller;
    private DefaultTableModel modelo;

    /**
     * Creates new form FormConsultaEstoqueGeral
     */
    public FormConsultaEstoqueGeral(IControllerFormConsultaEstoqueGeral var) {
        initComponents();
        
        controller = var;
        modelo = (DefaultTableModel) tblPesquisaEstoque.getModel();
        tblPesquisaEstoque.removeColumn(tblPesquisaEstoque.getColumnModel().getColumn(2));
        startcbox();
        this.setVisible(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTipo = new javax.swing.JLabel();
        cbxTipoElemento = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPesquisaEstoque = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        txtPesquisa = new javax.swing.JTextField();
        btnVer = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmVoltar = new javax.swing.JMenu();
        itmNovo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Consulta Estoque Geral");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblTipo.setText("Tipo:");

        cbxTipoElemento.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoElementoItemStateChanged(evt);
            }
        });

        tblPesquisaEstoque.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tipo", "Quantidade", "ID"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPesquisaEstoque.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tblPesquisaEstoque.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPesquisaEstoqueMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPesquisaEstoque);
        tblPesquisaEstoque.getColumnModel().getColumn(2).setResizable(false);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnVer.setText("Ver Lotes");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        itmVoltar.setText("Voltar");
        itmVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmVoltar);

        itmNovo.setText("CadastrarNovoElementoDeEstoque");
        itmNovo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmNovoMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmNovo);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 690, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(lblTipo)
                                .addGap(18, 18, 18)
                                .addComponent(cbxTipoElemento, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtPesquisa))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnPesquisar, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                            .addComponent(btnVer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTipo)
                    .addComponent(cbxTipoElemento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnVer))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPesquisar)
                    .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmVoltarMouseClicked(java.awt.event.MouseEvent evt) {        
        controller.cancelar();
    }    
    
    public void startcbox() {
        limparcbox();
        for (IEntidadeItemEstoque it : controller.carregaUtensilios()) {
            cbxTipoElemento.addItem(it.getNome());
        }
    }
    
    public void limparcbox() {
        cbxTipoElemento.removeAllItems();
        cbxTipoElemento.addItem("");
    }    
    
    private void itmNovoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmVoltarMouseClicked
        controller.abrirFormCadastrarItemEstoque();
    }//GEN-LAST:event_itmVoltarMouseClicked
    
    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing
    
    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        fazerPesquisa();
    }//GEN-LAST:event_btnPesquisarActionPerformed
    
    private void tblPesquisaEstoqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPesquisaEstoqueMouseClicked
        if (evt.getClickCount() > 1) {
            JTable target = (JTable) evt.getSource();
            controller.abrirTipoUtensilio((Long) modelo.getValueAt(target.getSelectedRow(), 2));
        }
    }//GEN-LAST:event_tblPesquisaEstoqueMouseClicked
    
    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        if (cbxTipoElemento.getSelectedIndex() > 0) {
            controller.abrirTipoUtensilio(controller.getIdUtensilio(String.valueOf(cbxTipoElemento.getSelectedItem())));
        }
    }//GEN-LAST:event_btnVerActionPerformed
    
    private void cbxTipoElementoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoElementoItemStateChanged
        if (cbxTipoElemento.getSelectedIndex() < 1) {
            btnVer.setEnabled(false);
        } else {
            btnVer.setEnabled(true);
        }
    }//GEN-LAST:event_cbxTipoElementoItemStateChanged
    
    public void limparTabela() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    
    public void fazerPesquisa() {
        limparTabela();
        for (IEntidadeItemEstoque it : controller.pesquisar(txtPesquisa.getText())) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{it.getNome(), it.getTotal(), it.getId()});
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnVer;
    private javax.swing.JComboBox cbxTipoElemento;
    private javax.swing.JMenu itmNovo;
    private javax.swing.JMenu itmVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblTipo;
    private javax.swing.JTable tblPesquisaEstoque;
    private javax.swing.JTextField txtPesquisa;
    // End of variables declaration//GEN-END:variables
}
