/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormEditarLista;
import br.mackenzie.simacr.interfaces.IEntidadeComUmaString;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class FormEditarLista extends javax.swing.JFrame {

    IControllerFormEditarLista controller;
    DefaultTableModel modelo;

    public FormEditarLista(IControllerFormEditarLista varController, String titulo) {
        initComponents();
        controller = varController;
        modelo = (DefaultTableModel) tblLista.getModel();
        tblLista.removeColumn(tblLista.getColumnModel().getColumn(1));
        carregarLista();
        this.setTitle(titulo);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblLista = new javax.swing.JTable();
        btnAddNovo = new javax.swing.JButton();
        btnRemover = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmVoltar = new javax.swing.JMenu();
        itmSalvar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblLista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID"
            }
        ));
        tblLista.setColumnSelectionAllowed(true);
        tblLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblLista.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(tblLista);
        tblLista.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        btnAddNovo.setText("Adicionar Novo");
        btnAddNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNovoActionPerformed(evt);
            }
        });

        btnRemover.setText("Remover Item");
        btnRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoverActionPerformed(evt);
            }
        });

        itmVoltar.setText("Voltar");
        itmVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmVoltar);

        itmSalvar.setText("Salvar");
        itmSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmSalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmSalvar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAddNovo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(btnRemover)
                .addContainerGap())
            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAddNovo)
                    .addComponent(btnRemover))
                .addGap(0, 17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNovoActionPerformed
        if (controller.adicionarNovo()) {
            carregarLista();
        }
    }//GEN-LAST:event_btnAddNovoActionPerformed

    private void btnRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoverActionPerformed
        if (tblLista.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecionar um item");
        } else {
            controller.remover((Long) modelo.getValueAt(tblLista.getSelectedRow(), 1));
            carregarLista();
        }
    }//GEN-LAST:event_btnRemoverActionPerformed

    private void itmVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmVoltarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_itmVoltarMouseClicked

    private void itmSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmSalvarMouseClicked
        if (tblLista.isEditing()) {
            tblLista.getCellEditor().stopCellEditing();
        }
        ArrayList<String> nomes = new ArrayList<String>();
        ArrayList<Long> ids = new ArrayList<Long>();
        int aux;
        for (aux = 0; aux < tblLista.getRowCount(); aux++) {
            nomes.add((String) modelo.getValueAt(aux, 0));
            ids.add((Long) modelo.getValueAt(aux, 1));
        }
        controller.salvar(nomes, ids);
    }//GEN-LAST:event_itmSalvarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    public void startFocus() {
        this.requestFocus();
    }

    public void carregarLista() {
        limparLista();
        for (IEntidadeComUmaString it : controller.getLista()) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{it.getNome(), it.getId()});
        }
    }

    public void limparLista() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNovo;
    private javax.swing.JButton btnRemover;
    private javax.swing.JMenu itmSalvar;
    private javax.swing.JMenu itmVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblLista;
    // End of variables declaration//GEN-END:variables
}
