/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormCadastroTripulante;
import br.mackenzie.simacr.interfaces.ITripulante;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class FormCadastroTripulante extends javax.swing.JFrame {

    private IControllerFormCadastroTripulante controller;

    public FormCadastroTripulante(IControllerFormCadastroTripulante var, ITripulante varTripulante) {
        controller = var;
        initComponents();

        if (varTripulante == null) {
            menuExluir.setVisible(false);
        } else {
            menuSalvar.setText("Atualizar");
            txtNome.setText(varTripulante.getNome());
            ftxtDataNascimento.setText(varTripulante.getNascimento());
            txtNaturalidade.setText(varTripulante.getNaturalidade());
            ftxtTelefone.setText(varTripulante.getTelefone());
            cbxProfissao.setSelectedItem(varTripulante.getProfissao());
            cbxSexo.setSelectedItem(varTripulante.getSexo());
            txtLogin.setText(varTripulante.getILogin().getNome());
            txtSenha.setText(varTripulante.getILogin().getSenha());
        }
        this.setVisible(true);
        this.startFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadastroTripulante = new javax.swing.JPanel();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblDataNascimento = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox();
        lblNaturalidade = new javax.swing.JLabel();
        txtNaturalidade = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        ftxtTelefone = new javax.swing.JFormattedTextField();
        lblProfissao = new javax.swing.JLabel();
        cbxProfissao = new javax.swing.JComboBox();
        ftxtDataNascimento = new javax.swing.JFormattedTextField();
        lblLogin = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        lblSenha = new javax.swing.JLabel();
        txtSenha = new javax.swing.JTextField();
        menuOpcoes = new javax.swing.JMenuBar();
        menuCancelar = new javax.swing.JMenu();
        menuSalvar = new javax.swing.JMenu();
        menuExluir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Cadastro de Tripulantes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNome.setText("Nome");

        lblDataNascimento.setText("Data de Nascimento");

        lblSexo.setText("Sexo");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        lblNaturalidade.setText("Naturalidade");

        lblTelefone.setText("Telefone");

        try {
            ftxtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        lblProfissao.setText("Profissão");

        cbxProfissao.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Dentista", "Enfermeiro", "Farmacêutico", "Médico", "Recepcionista", "Administrador" }));

        try {
            ftxtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        ftxtDataNascimento.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        lblLogin.setText("Login");

        lblSenha.setText("Senha");

        javax.swing.GroupLayout jpCadastroTripulanteLayout = new javax.swing.GroupLayout(jpCadastroTripulante);
        jpCadastroTripulante.setLayout(jpCadastroTripulanteLayout);
        jpCadastroTripulanteLayout.setHorizontalGroup(
            jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroTripulanteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtLogin)
                        .addComponent(ftxtTelefone, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)
                        .addComponent(lblNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblSexo, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblTelefone, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(lblLogin))
                .addGap(58, 58, 58)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCadastroTripulanteLayout.createSequentialGroup()
                        .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDataNascimento, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ftxtDataNascimento)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jpCadastroTripulanteLayout.createSequentialGroup()
                                .addComponent(cbxProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(58, 58, 58))
                    .addGroup(jpCadastroTripulanteLayout.createSequentialGroup()
                        .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaturalidade)
                            .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jpCadastroTripulanteLayout.createSequentialGroup()
                        .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSenha)
                            .addComponent(lblProfissao)
                            .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jpCadastroTripulanteLayout.setVerticalGroup(
            jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastroTripulanteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblDataNascimento))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ftxtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNaturalidade)
                    .addComponent(lblSexo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(lblProfissao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ftxtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLogin)
                    .addComponent(lblSenha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCadastroTripulanteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        menuCancelar.setText("Voltar");
        menuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCancelarMouseClicked(evt);
            }
        });
        menuOpcoes.add(menuCancelar);

        menuSalvar.setText("Salvar");
        menuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalvarMouseClicked(evt);
            }
        });
        menuOpcoes.add(menuSalvar);

        menuExluir.setText("Excluir");
        menuExluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExluirMouseClicked(evt);
            }
        });
        menuOpcoes.add(menuExluir);

        setJMenuBar(menuOpcoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastroTripulante, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCadastroTripulante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void startFocus() {
        txtNome.requestFocus();
    }
    private void menuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalvarMouseClicked
        if ((txtNome.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Escrever o nome");
        } else if ((txtNaturalidade.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Escrever naturalidade");
        } else if ((txtLogin.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Definir o login");
        } else if ((txtSenha.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Definir a senha");
        } else if (ftxtDataNascimento.isValid() == false) {
            JOptionPane.showMessageDialog(this, "Preencher a data de nascimento");
        } else if (ftxtTelefone.isValid() == false) {
            JOptionPane.showMessageDialog(this, "Preencher o telefone");
        } else {
            String dtNasc = ftxtDataNascimento.getText();
            System.out.println(dtNasc);
            controller.salvar(txtNome.getText(), dtNasc, txtNaturalidade.getText(), ftxtTelefone.getText(), String.valueOf(cbxProfissao.getSelectedItem()), String.valueOf(cbxSexo.getSelectedItem()), String.valueOf(txtLogin.getText()), String.valueOf(txtSenha.getText()));
        }
    }//GEN-LAST:event_menuSalvarMouseClicked

    private void menuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCancelarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_menuCancelarMouseClicked

    private void menuExluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExluirMouseClicked
        controller.excluir();
    }//GEN-LAST:event_menuExluirMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cbxProfissao;
    private javax.swing.JComboBox cbxSexo;
    private javax.swing.JFormattedTextField ftxtDataNascimento;
    private javax.swing.JFormattedTextField ftxtTelefone;
    private javax.swing.JPanel jpCadastroTripulante;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblLogin;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblSenha;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JMenu menuCancelar;
    private javax.swing.JMenu menuExluir;
    private javax.swing.JMenuBar menuOpcoes;
    private javax.swing.JMenu menuSalvar;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
