/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormFilaAviamento;
import br.mackenzie.simacr.interfaces.IFilaAviamento;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class FormFilaAviamento extends javax.swing.JFrame {

    private IControllerFormFilaAviamento controller;
    private DefaultTableModel modelo;

    /**
     * Creates new form FormFilaAviamento
     */
    public FormFilaAviamento(IControllerFormFilaAviamento var) {
        initComponents();
        controller = var;
        modelo = (DefaultTableModel) tblFilaReceitas.getModel();
        tblFilaReceitas.removeColumn(tblFilaReceitas.getColumnModel().getColumn(0));
        this.setVisible(true);
        this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFilaReceitas = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmVoltar = new javax.swing.JMenu();
        itmCarregarFila = new javax.swing.JMenu();
        itmMedicamentos = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Fila de Aviamentos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblFilaReceitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NomePaciente"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblFilaReceitas.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblFilaReceitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblFilaReceitasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblFilaReceitas);
        tblFilaReceitas.getColumnModel().getColumn(0).setResizable(false);
        tblFilaReceitas.getColumnModel().getColumn(0).setPreferredWidth(10);
        tblFilaReceitas.getColumnModel().getColumn(1).setResizable(false);
        tblFilaReceitas.getColumnModel().getColumn(1).setPreferredWidth(150);

        itmVoltar.setText("Voltar");
        itmVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmVoltar);

        itmCarregarFila.setText("CarregarFila");
        itmCarregarFila.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmCarregarFilaMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmCarregarFila);

        itmMedicamentos.setText("ManutençãoDeMedicamentos");
        itmMedicamentos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmMedicamentosMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmMedicamentos);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmVoltarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_itmVoltarMouseClicked

    private void itmMedicamentosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmMedicamentosMouseClicked
        controller.abrirManutencaoMedicamento();
    }//GEN-LAST:event_itmMedicamentosMouseClicked

    private void tblFilaReceitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblFilaReceitasMouseClicked
        if (evt.getClickCount() > 1) {
            JTable target = (JTable) evt.getSource();
            controller.abrirReceitaMedicamentos((Long) modelo.getValueAt(target.getSelectedRow(), 0));
            limparTabela();
        }
    }//GEN-LAST:event_tblFilaReceitasMouseClicked

    private void itmCarregarFilaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmCarregarFilaMouseClicked
        limparTabela();
        for (IFilaAviamento fila : controller.carregarFila()) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{fila.getId(), fila.getNome()});
        }
    }//GEN-LAST:event_itmCarregarFilaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    public void refresh() {
        itmCarregarFilaMouseClicked(null);
    }

    private void limparTabela() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu itmCarregarFila;
    private javax.swing.JMenu itmMedicamentos;
    private javax.swing.JMenu itmVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFilaReceitas;
    // End of variables declaration//GEN-END:variables
}
