/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormFilaConsulta;
import br.mackenzie.simacr.interfaces.IFilaConsulta;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class FormFilaConsulta extends javax.swing.JFrame {

    /**
     * Creates new form FormFilaConsultaMedica1
     */
    IControllerFormFilaConsulta controller;
    DefaultTableModel modelo;

    public FormFilaConsulta(IControllerFormFilaConsulta var, boolean tipo) {
        initComponents();
        controller = var;
        modelo = (DefaultTableModel) tblPaciente.getModel();
        tblPaciente.removeColumn(tblPaciente.getColumnModel().getColumn(0));
        if (tipo) {
            this.setTitle("Simacr 2.0 - Fila de Consultas Médicas");
        } else {
            this.setTitle("Simacr 2.0 - Fila de Consultas Odontológicas");
        }
        this.setVisible(true);
        this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        tblPaciente = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVolta = new javax.swing.JMenu();
        mnuCarregar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Fila Consulta Medica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        tblPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Temperatura", "Urgente"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Double.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPaciente.getTableHeader().setReorderingAllowed(false);
        tblPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblPaciente);
        tblPaciente.getColumnModel().getColumn(2).setResizable(false);

        mnuVolta.setText("Voltar");
        mnuVolta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuVoltaMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuVolta);

        mnuCarregar.setText("CarregarTriagens");
        mnuCarregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCarregarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCarregar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparTabela() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }

    public void refresh() {
        mnuCarregarMouseClicked(null);
    }
    private void mnuVoltaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuVoltaMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_mnuVoltaMouseClicked

    private void mnuCarregarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCarregarMouseClicked
        limparTabela();
        for (IFilaConsulta f : controller.buscaTriagens()) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{f.getId(), f.getNome(),f.getTemperatura(),f.getTemperatura()>38});
        }
    }//GEN-LAST:event_mnuCarregarMouseClicked

    private void tblPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacienteMouseClicked
        if (evt.getClickCount() > 1) {
            JTable target = (JTable) evt.getSource();
            controller.abrirProntuario((Long) modelo.getValueAt(target.getSelectedRow(), 0));
            limparTabela();
        }
    }//GEN-LAST:event_tblPacienteMouseClicked

        private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JMenu mnuCarregar;
    private javax.swing.JMenu mnuVolta;
    private javax.swing.JTable tblPaciente;
    // End of variables declaration//GEN-END:variables
}
