/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormDadosItemEstoque;
import br.mackenzie.simacr.interfaces.ILoteItemEstoque;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author H_W
 */
public class FormDadosItemEstoque extends javax.swing.JFrame {

    IControllerFormDadosItemEstoque controller;
    DefaultTableModel modelo;

    public FormDadosItemEstoque(IControllerFormDadosItemEstoque var) {
        controller = var;
        initComponents();
        modelo = (DefaultTableModel) tblLotes.getModel();
        tblLotes.removeColumn(tblLotes.getColumnModel().getColumn(0));
        lblNomeVar.setText(controller.buscarNome());
        update();
        this.setVisible(true);
    }

    private void popula() {
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
        for (ILoteItemEstoque it : controller.buscarLotes()) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{it.getId(), it.getNumeroLote(), it.getQuantidade()});
        }
    }
    
    public void update()
    {
        atualizarDados();
        popula();        
    }

    private void atualizarDados() {
        lblTotal.setText(controller.buscarTotal());
        lblSemLote.setText(controller.buscarParcial());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblNomeVar = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblTotal = new javax.swing.JLabel();
        lblSemLote = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmCancelar = new javax.swing.JMenu();
        itmRemover = new javax.swing.JMenu();
        itmExcluir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Consulta de Lotes");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNome.setText("Nome Utensilio:");

        lblNomeVar.setText("aaaa");

        jLabel1.setText("Quantidade Total:");

        jLabel2.setText("Quantidade sem lote:");

        lblTotal.setText("bbbb");

        lblSemLote.setText("cccc");

        btnExcluir.setText("Excluir Lote");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NumeroLote", "Quantidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLotes);

        itmCancelar.setText("Voltar");
        itmCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmCancelar);

        itmRemover.setText("RemoverQuantidade");
        itmRemover.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmRemoverMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmRemover);

        itmExcluir.setText("ExcluirUtensilio");
        itmExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmExcluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNome)
                                    .addComponent(jLabel1))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTotal)
                                    .addComponent(lblNomeVar)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblSemLote)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 5, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnExcluir)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(lblNomeVar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblSemLote))
                .addGap(18, 18, 18)
                .addComponent(btnExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itmCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmCancelarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_itmCancelarMouseClicked

    private void itmRemoverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmRemoverMouseClicked
        try {
            Integer quantidade = Integer.valueOf(JOptionPane.showInputDialog(this, "Quantidade a ser removida"));
            if(quantidade>Integer.valueOf(controller.buscarParcial()))
            {
                JOptionPane.showMessageDialog(this, "Quantidade insuficiente no estoque");
                return;
            }
            controller.remover(quantidade);
        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Escreva numeros inteiros");
        }
    }//GEN-LAST:event_itmRemoverMouseClicked

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblLotes.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecionar uma consulta");
        } else {

            controller.excluirLote((Long) modelo.getValueAt(tblLotes.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void itmExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmExcluirMouseClicked
        controller.excluir();
    }//GEN-LAST:event_itmExcluirMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JMenu itmCancelar;
    private javax.swing.JMenu itmExcluir;
    private javax.swing.JMenu itmRemover;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblNomeVar;
    private javax.swing.JLabel lblSemLote;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JTable tblLotes;
    // End of variables declaration//GEN-END:variables
}
