/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.ControllerFormTelaBase;
import br.mackenzie.simacr.controllers.interfaces.IControllerFormTelaBase;
import br.mackenzie.simacr.interfaces.ITripulante;

/**
 *
 * @author root
 */
public class FormTelaBase extends javax.swing.JFrame {

    private IControllerFormTelaBase controller;

    public FormTelaBase(IControllerFormTelaBase var, String profissao) {
        initComponents();
        controller = var;

        if ("Dentista".equals(profissao)) {
            btnConsultaOdonto.setVisible(true);
            btnConsultaMedica.setVisible(false);
            btnFarmacia.setVisible(false);
            btnRecepcao.setVisible(false);
            btnTripulante.setVisible(false);
            btnTriagem.setVisible(false);
            btnEstoqueGeral.setVisible(false);
        } else if ("Médico".equals(profissao)) {
            btnConsultaOdonto.setVisible(false);
            btnConsultaMedica.setVisible(true);
            btnFarmacia.setVisible(false);
            btnRecepcao.setVisible(false);
            btnTripulante.setVisible(false);
            btnTriagem.setVisible(false);
            btnEstoqueGeral.setVisible(false);
        } else if ("Enfermeiro".equals(profissao)) {
            btnConsultaOdonto.setVisible(false);
            btnConsultaMedica.setVisible(false);
            btnFarmacia.setVisible(false);
            btnRecepcao.setVisible(false);
            btnTripulante.setVisible(false);
            btnTriagem.setVisible(true);
            btnEstoqueGeral.setVisible(true);
        } else if ("Recepcionista".equals(profissao)) {
            btnConsultaOdonto.setVisible(false);
            btnConsultaMedica.setVisible(false);
            btnFarmacia.setVisible(false);
            btnRecepcao.setVisible(true);
            btnTripulante.setVisible(false);
            btnTriagem.setVisible(false);
            btnEstoqueGeral.setVisible(true);
        } else if ("Farmacêutico".equals(profissao)) {
            btnConsultaOdonto.setVisible(false);
            btnConsultaMedica.setVisible(false);
            btnFarmacia.setVisible(true);
            btnRecepcao.setVisible(false);
            btnTripulante.setText("Receita para tripulante");
            btnTripulante.setVisible(true);
            btnTriagem.setVisible(false);
            btnEstoqueGeral.setVisible(true);
        }
        this.setVisible(true);
        this.startFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRecepcao = new javax.swing.JButton();
        btnConsultaMedica = new javax.swing.JButton();
        btnConsultaOdonto = new javax.swing.JButton();
        btnFarmacia = new javax.swing.JButton();
        btnTripulante = new javax.swing.JButton();
        btnTriagem = new javax.swing.JButton();
        btnEstoqueGeral = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmVoltar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0-Tela Base");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        btnRecepcao.setText("Recepção");
        btnRecepcao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecepcaoActionPerformed(evt);
            }
        });

        btnConsultaMedica.setText("Consulta Médica");
        btnConsultaMedica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaMedicaActionPerformed(evt);
            }
        });

        btnConsultaOdonto.setText("Consulta Odontológica");
        btnConsultaOdonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultaOdontoActionPerformed(evt);
            }
        });

        btnFarmacia.setText("Farmácia");
        btnFarmacia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFarmaciaActionPerformed(evt);
            }
        });

        btnTripulante.setText("Manutenção de Tripulantes");
        btnTripulante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTripulanteActionPerformed(evt);
            }
        });

        btnTriagem.setText("Triagem");
        btnTriagem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTriagemActionPerformed(evt);
            }
        });

        btnEstoqueGeral.setText("Estoque de Utensílios");
        btnEstoqueGeral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEstoqueGeralActionPerformed(evt);
            }
        });

        itmVoltar.setText("Voltar");
        itmVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmVoltar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEstoqueGeral, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnTripulante, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnConsultaOdonto, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnConsultaMedica, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnRecepcao, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnTriagem, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                    .addComponent(btnFarmacia, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                .addGap(0, 30, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(btnRecepcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTriagem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultaMedica)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnConsultaOdonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnFarmacia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTripulante)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEstoqueGeral)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecepcaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecepcaoActionPerformed
        controller.abrirNovaJanela("Recepcao");
    }//GEN-LAST:event_btnRecepcaoActionPerformed

    private void btnTriagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTriagemActionPerformed
        controller.abrirNovaJanela("Triagem");
    }//GEN-LAST:event_btnTriagemActionPerformed

    private void btnConsultaMedicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaMedicaActionPerformed
        controller.abrirNovaJanela("ConsultaMedica");
    }//GEN-LAST:event_btnConsultaMedicaActionPerformed

    private void btnConsultaOdontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultaOdontoActionPerformed
        controller.abrirNovaJanela("ConsultaOdontologica");
    }//GEN-LAST:event_btnConsultaOdontoActionPerformed

    private void btnFarmaciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFarmaciaActionPerformed
        controller.abrirNovaJanela("Farmacia");
    }//GEN-LAST:event_btnFarmaciaActionPerformed

    private void btnTripulanteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTripulanteActionPerformed
        controller.abrirNovaJanela("ManutencaoTripulante");
    }//GEN-LAST:event_btnTripulanteActionPerformed

    private void itmVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmVoltarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_itmVoltarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void btnEstoqueGeralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEstoqueGeralActionPerformed
        controller.abrirNovaJanela("ConsultaEstoqueGeral");
    }//GEN-LAST:event_btnEstoqueGeralActionPerformed

    public void startFocus() {
        btnRecepcao.requestFocus();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnConsultaMedica;
    private javax.swing.JButton btnConsultaOdonto;
    private javax.swing.JButton btnEstoqueGeral;
    private javax.swing.JButton btnFarmacia;
    private javax.swing.JButton btnRecepcao;
    private javax.swing.JButton btnTriagem;
    private javax.swing.JButton btnTripulante;
    private javax.swing.JMenu itmVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
