/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormProntuario;
import br.mackenzie.simacr.interfaces.IConsultaMedica;
import br.mackenzie.simacr.interfaces.IConsultaOdontologica;
import br.mackenzie.simacr.interfaces.IPaciente;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class FormProntuario extends javax.swing.JFrame {

    IControllerFormProntuario controller;
    private DefaultTableModel modelo;

    public FormProntuario(IControllerFormProntuario varController, IPaciente varPaciente, boolean tipo) {
        initComponents();
        controller = varController;
        modelo = (DefaultTableModel) tblConsulta.getModel();
        populaDadosPaciente(varPaciente);
        if (tipo) {
            initTableMedico();
            populaConsultaMedica();
        }
        else
        {
            initTableDentista();
        }
        this.setVisible(true);
    }

    private void populaConsultaMedica() {
        ArrayList<IConsultaMedica> var = controller.buscarConsultasMedica();
        for (IConsultaMedica cm : var) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{cm.getId(), cm.getDataConsulta(), cm.getSintoma(),cm.getHipoteseDiagnostica(),cm.getResponsavel().getNome()});
        }
    }
    
    private void populaConsultaOdontologica() {
        ArrayList<IConsultaOdontologica> var = controller.buscarConsultasOdontologicas();
        for (IConsultaOdontologica cm : var) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{cm.getId(), cm.getDataConsulta(), cm.getObservacao(),cm.getEvolucao(),cm.getResponsavel().getNome()});
        }
    }    

    private void populaDadosPaciente(IPaciente var) {
        txtNome.setText(var.getNome());
        txtData_Nascimento.setText(var.getDataNascimento());
        txtCor.setText(var.getCor());
        txtComunidade.setText(var.getComunidade());
        txtRio.setText(var.getRio());
        txtProfissao.setText(var.getProfissao());
        txtTelefone.setText(var.getTelefone());
        txtNaturalidade.setText(var.getNaturalidade());
        txtEstado_Civil.setText(var.getEstadoCivil());
        if (var.getSexo().equals("Masculino")) {
            rbtnMasculino.setSelected(true);
        } else {
            rbtnFeminino.setSelected(true);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lblNome = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        lblCor = new javax.swing.JLabel();
        txtCor = new javax.swing.JTextField();
        lblComunidade = new javax.swing.JLabel();
        txtComunidade = new javax.swing.JTextField();
        lblRio = new javax.swing.JLabel();
        txtRio = new javax.swing.JTextField();
        lblProfissão = new javax.swing.JLabel();
        txtProfissao = new javax.swing.JTextField();
        lblTelefone = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        lblNaturalidade = new javax.swing.JLabel();
        txtNaturalidade = new javax.swing.JTextField();
        lblEstado_Civil = new javax.swing.JLabel();
        txtEstado_Civil = new javax.swing.JTextField();
        lblSexo = new javax.swing.JLabel();
        rbtnMasculino = new javax.swing.JRadioButton();
        rbtnFeminino = new javax.swing.JRadioButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblConsulta = new javax.swing.JTable();
        Data_Nascimento = new javax.swing.JLabel();
        txtData_Nascimento = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuVoltar = new javax.swing.JMenu();
        mnuVer = new javax.swing.JMenu();
        mnuNova_Consulta = new javax.swing.JMenu();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Prontuário Médico");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNome.setText("Nome");

        txtNome.setEnabled(false);

        lblCor.setText("Cor");

        txtCor.setEnabled(false);

        lblComunidade.setText("Comunidade");

        txtComunidade.setEnabled(false);

        lblRio.setText("Rio");

        txtRio.setEnabled(false);

        lblProfissão.setText("Profissão");

        txtProfissao.setEnabled(false);

        lblTelefone.setText("Telefone");

        txtTelefone.setText("(   )   - ");
        txtTelefone.setEnabled(false);

        lblNaturalidade.setText("Naturalidade");

        txtNaturalidade.setEnabled(false);

        lblEstado_Civil.setText("Estado Civil");

        txtEstado_Civil.setEnabled(false);

        lblSexo.setText("Sexo");

        rbtnMasculino.setText("Masculino");
        rbtnMasculino.setEnabled(false);

        rbtnFeminino.setText("Feminino");
        rbtnFeminino.setEnabled(false);

        tblConsulta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "IDConsulta", "Data", "Hipótese", "Diagnóstico", "Médico"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblConsulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblConsultaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblConsulta);
        tblConsulta.getColumnModel().getColumn(0).setResizable(false);
        tblConsulta.getColumnModel().getColumn(1).setResizable(false);
        tblConsulta.getColumnModel().getColumn(2).setResizable(false);
        tblConsulta.getColumnModel().getColumn(3).setResizable(false);
        tblConsulta.getColumnModel().getColumn(4).setResizable(false);

        Data_Nascimento.setText("Data de Nascimento");

        txtData_Nascimento.setEnabled(false);

        mnuVoltar.setText("Voltar");
        mnuVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuVoltar);

        mnuVer.setText("Ver");
        mnuVer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuVerMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuVer);

        mnuNova_Consulta.setText("Nova Consuta");
        mnuNova_Consulta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuNova_ConsultaMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuNova_Consulta);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblNome)
                            .addGap(432, 432, 432))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtProfissao)
                                    .addComponent(lblCor)
                                    .addComponent(txtCor)
                                    .addComponent(lblProfissão)
                                    .addComponent(txtEstado_Civil, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE))
                                .addComponent(lblEstado_Civil))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(lblSexo)
                                .addComponent(txtComunidade, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(lblComunidade)
                                    .addGap(151, 151, 151))
                                .addComponent(txtTelefone)
                                .addComponent(lblTelefone)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(rbtnMasculino)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(rbtnFeminino)))))
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRio)
                    .addComponent(lblNaturalidade)
                    .addComponent(Data_Nascimento)
                    .addComponent(txtData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtRio, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
            .addComponent(jScrollPane2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(Data_Nascimento))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtData_Nascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRio)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtRio, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lblComunidade)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblCor)
                        .addGap(18, 18, 18)
                        .addComponent(txtCor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblProfissão)
                        .addGap(18, 18, 18)
                        .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNaturalidade)
                            .addComponent(lblTelefone))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEstado_Civil)
                    .addComponent(lblSexo))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEstado_Civil, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rbtnMasculino)
                    .addComponent(rbtnFeminino))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblConsultaMouseClicked
        //ir em 2x cliques
        if (evt.getClickCount() > 1) {
            JTable target = (JTable) evt.getSource();
            controller.abrirConsultaMedica((Long) modelo.getValueAt(target.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_tblConsultaMouseClicked

    private void mnuVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuVoltarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_mnuVoltarMouseClicked

    private void initTableMedico() {
        modelo = (DefaultTableModel) tblConsulta.getModel();
        modelo.setDataVector(new Object[][]{}, new Object[]{"IDConsulta", "Data", "Hipótese", "Diagnóstico", "Responśavel"});
        tblConsulta.removeColumn(tblConsulta.getColumnModel().getColumn(0));
    }
    
    private void initTableDentista()
    {
        modelo = (DefaultTableModel) tblConsulta.getModel();
        modelo.setDataVector(new Object[][]{}, new Object[]{"IDConsulta", "Data", "Observação","Evolução", "Responśavel"});
        tblConsulta.removeColumn(tblConsulta.getColumnModel().getColumn(0));
    }

    private void mnuVerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuVerMouseClicked
        if (tblConsulta.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Selecionar uma consulta");
        } else {

            controller.abrirConsultaMedica((Long) tblConsulta.getValueAt(tblConsulta.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_mnuVerMouseClicked

    private void mnuNova_ConsultaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuNova_ConsultaMouseClicked
        controller.abrirConsultaMedica(-1L);
    }//GEN-LAST:event_mnuNova_ConsultaMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Data_Nascimento;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblComunidade;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblEstado_Civil;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProfissão;
    private javax.swing.JLabel lblRio;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JMenu mnuNova_Consulta;
    private javax.swing.JMenu mnuVer;
    private javax.swing.JMenu mnuVoltar;
    private javax.swing.JRadioButton rbtnFeminino;
    private javax.swing.JRadioButton rbtnMasculino;
    private javax.swing.JTable tblConsulta;
    private javax.swing.JTextField txtComunidade;
    private javax.swing.JTextField txtCor;
    private javax.swing.JTextField txtData_Nascimento;
    private javax.swing.JTextField txtEstado_Civil;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JTextField txtRio;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
