/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormCadastroPaciente;
import br.mackenzie.simacr.interfaces.IEntidadeComUmaString;
import br.mackenzie.simacr.interfaces.IPaciente;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class FormCadastroPaciente extends javax.swing.JFrame {

    IControllerFormCadastroPaciente controller;

    /**
     * Creates new form FormCadastroPaciente
     */
    public FormCadastroPaciente(IControllerFormCadastroPaciente varController, IPaciente varPaciente) {
        controller = varController;
        initComponents();
        if (varPaciente == null) {
            itmExcluir.setVisible(false);
            startCbox(0);
        } else {
            itmSalvar.setText("Atualizar");
            txtNome.setText(varPaciente.getNome());
            txtDataNascimento.setText(varPaciente.getDataNascimento());
            txtNacionalidade.setText(varPaciente.getNacionalidade());
            txtNaturalidade.setText(varPaciente.getNaturalidade());
            txtProfissao.setText(varPaciente.getProfissao());
            startCbox(4);
            carregarRios(varPaciente.getRio());
            carregarCorPele(varPaciente.getCor());
            carregarComunidade(varPaciente.getComunidade());
            txtTelefone.setText((varPaciente.getTelefone()));
            cboxEstadoCivil.setSelectedItem(varPaciente.getEstadoCivil());
            cboxSexo.setSelectedItem(varPaciente.getSexo());
        }
        this.setVisible(true);
        this.startFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNome = new javax.swing.JLabel();
        lblDataNascimento = new javax.swing.JLabel();
        lblProfissao = new javax.swing.JLabel();
        lblCor = new javax.swing.JLabel();
        lblNacionalidade = new javax.swing.JLabel();
        lblNaturalidade = new javax.swing.JLabel();
        lblComunidade = new javax.swing.JLabel();
        lblRio = new javax.swing.JLabel();
        lblEstadoCivil = new javax.swing.JLabel();
        lblSexo = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtProfissao = new javax.swing.JTextField();
        txtDataNascimento = new javax.swing.JFormattedTextField();
        txtTelefone = new javax.swing.JFormattedTextField();
        txtNaturalidade = new javax.swing.JTextField();
        txtNacionalidade = new javax.swing.JTextField();
        cboxEstadoCivil = new javax.swing.JComboBox();
        cboxSexo = new javax.swing.JComboBox();
        cboxCor = new javax.swing.JComboBox();
        cboxComunidade = new javax.swing.JComboBox();
        cboxRio = new javax.swing.JComboBox();
        btnEditComunidade = new javax.swing.JButton();
        btnEditRio = new javax.swing.JButton();
        btnEditarCor = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        itmVoltar = new javax.swing.JMenu();
        itmSalvar = new javax.swing.JMenu();
        itmExcluir = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 -Cadastrar Paciente");
        setPreferredSize(new java.awt.Dimension(650, 408));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNome.setText("Nome");

        lblDataNascimento.setText("DataNascimento");

        lblProfissao.setText("Profissão");

        lblCor.setText("Cor");

        lblNacionalidade.setText("Nacionalidade");

        lblNaturalidade.setText("Naturalidade");

        lblComunidade.setText("Comunidade");

        lblRio.setText("Rio");

        lblEstadoCivil.setText("Estado Civil");

        lblSexo.setText("Sexo");

        lblTelefone.setText("Telefone");

        try {
            txtDataNascimento.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtDataNascimento.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        try {
            txtTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        txtTelefone.setFocusLostBehavior(javax.swing.JFormattedTextField.COMMIT);

        cboxEstadoCivil.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Solteiro", "Casado", "Viuvo" }));

        cboxSexo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Masculino", "Feminino" }));

        cboxRio.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxRioItemStateChanged(evt);
            }
        });

        btnEditComunidade.setText("Editar Lista");
        btnEditComunidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditComunidadeActionPerformed(evt);
            }
        });

        btnEditRio.setText("Editar Lista");
        btnEditRio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditRioActionPerformed(evt);
            }
        });

        btnEditarCor.setText("Editar Lista");
        btnEditarCor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCorActionPerformed(evt);
            }
        });

        itmVoltar.setText("Voltar");
        itmVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmVoltarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmVoltar);

        itmSalvar.setText("Salvar");
        itmSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmSalvarMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmSalvar);

        itmExcluir.setText("Excluir");
        itmExcluir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                itmExcluirMouseClicked(evt);
            }
        });
        jMenuBar1.add(itmExcluir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnEditComunidade)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblComunidade)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(cboxComunidade, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEditRio)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblRio)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cboxRio, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblSexo)
                                        .addComponent(lblProfissao)
                                        .addComponent(lblNome)
                                        .addComponent(lblEstadoCivil))
                                    .addGap(14, 14, 14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(cboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblDataNascimento)
                            .addGap(18, 18, 18)
                            .addComponent(txtDataNascimento))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTelefone)
                            .addGap(54, 54, 54)
                            .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lblNacionalidade)
                                .addComponent(lblNaturalidade)
                                .addComponent(lblCor))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cboxCor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNaturalidade)
                                .addComponent(txtNacionalidade))))
                    .addComponent(btnEditarCor, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNome)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDataNascimento)
                    .addComponent(txtDataNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfissao)
                    .addComponent(txtProfissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTelefone)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboxEstadoCivil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEstadoCivil)
                    .addComponent(lblNaturalidade)
                    .addComponent(txtNaturalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSexo)
                    .addComponent(cboxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNacionalidade)
                    .addComponent(txtNacionalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRio)
                    .addComponent(cboxRio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCor)
                    .addComponent(cboxCor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEditRio)
                    .addComponent(btnEditarCor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComunidade)
                    .addComponent(cboxComunidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEditComunidade)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void startFocus() {
        txtNome.requestFocus();
    }

    public void startCbox(int tipo) {
        switch (tipo) {
            case (0):
                cboxComunidade.setEnabled(false);
                limparcboxcomunidade("");
                carregarRios("");
                carregarCorPele("");
                break;
            case (1):
                carregarCorPele("");
                break;
            case (2):
                cboxComunidade.setEnabled(false);
                limparcboxcomunidade("");
                carregarRios("");
                break;
            case (3):
                limparcboxcomunidade("");
                carregarComunidade("");
                break;
            case (4):
                cboxComunidade.setEnabled(true);
                btnEditComunidade.setVisible(false);
                btnEditRio.setVisible(false);
                btnEditarCor.setVisible(false);
        }

    }

    private void itmVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmVoltarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_itmVoltarMouseClicked

    private void itmSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmSalvarMouseClicked
        if ((txtNome.getText().trim()).equals("")) {
            JOptionPane.showMessageDialog(this, "Informar o nome");
        } else if (String.valueOf(cboxRio.getSelectedItem()).equals("")) {
            JOptionPane.showMessageDialog(this, "Informar o rio");
        } else if (String.valueOf(cboxComunidade.getSelectedItem()).equals("")) {
            JOptionPane.showMessageDialog(this, "Informar a comunidade");
        } else if (txtDataNascimento.isValid() == false) {
            JOptionPane.showMessageDialog(this, "Preencher a data de nascimento");
        } else {
            controller.salvar(txtNome.getText(), txtProfissao.getText(), String.valueOf(cboxComunidade.getSelectedItem()), String.valueOf(cboxRio.getSelectedItem()), txtDataNascimento.getText(), txtTelefone.getText(), String.valueOf(cboxCor.getSelectedItem()), txtNaturalidade.getText(), txtNacionalidade.getText(), String.valueOf(cboxEstadoCivil.getSelectedItem()), String.valueOf(cboxSexo.getSelectedItem()));
        }
    }//GEN-LAST:event_itmSalvarMouseClicked

    private void itmExcluirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_itmExcluirMouseClicked
        controller.excluir();
    }//GEN-LAST:event_itmExcluirMouseClicked

    private void btnEditComunidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditComunidadeActionPerformed
        controller.editarComunidades(String.valueOf(cboxRio.getSelectedItem()));
    }//GEN-LAST:event_btnEditComunidadeActionPerformed

    private void btnEditRioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditRioActionPerformed
        controller.editarRios();
    }//GEN-LAST:event_btnEditRioActionPerformed

    private void btnEditarCorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCorActionPerformed
        controller.editarCorDePeles();
    }//GEN-LAST:event_btnEditarCorActionPerformed

    private void cboxRioItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxRioItemStateChanged
        if (cboxRio.getSelectedIndex() < 1) {
            String var = controller.iniciarcboxcomu();
            if (var == null) {
                carregarComunidade("");
                cboxComunidade.setEnabled(true);
            } else {
                carregarComunidade(var);
                cboxComunidade.setEnabled(true);
            }
        } else {
            carregarComunidade("");
            cboxComunidade.setEnabled(true);
        }
    }//GEN-LAST:event_cboxRioItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void carregarRios(String primeiro) {
        limparcboxrio(primeiro);
        for (IEntidadeComUmaString it : controller.carregaRio()) {
            cboxRio.addItem(it.getNome());
        }
    }

    private void carregarCorPele(String primeiro) {
        limparcboxcorpele(primeiro);
        for (IEntidadeComUmaString it : controller.carregaCorPele()) {
            cboxCor.addItem(it.getNome());
        }
    }

    private void carregarComunidade(String primeiro) {
        limparcboxcomunidade(primeiro);
        for (IEntidadeComUmaString it : controller.carregaComunidade(String.valueOf(cboxRio.getSelectedItem()))) {
            cboxComunidade.addItem(it.getNome());
        }
    }

    private void limparcboxcomunidade(String primeiro) {
        cboxComunidade.removeAllItems();
        cboxComunidade.addItem(primeiro);
    }

    private void limparcboxrio(String primeiro) {
        cboxRio.removeAllItems();
        cboxRio.addItem(primeiro);
    }

    private void limparcboxcorpele(String primeiro) {
        cboxCor.removeAllItems();
        cboxCor.addItem(primeiro);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditComunidade;
    private javax.swing.JButton btnEditRio;
    private javax.swing.JButton btnEditarCor;
    private javax.swing.JComboBox cboxComunidade;
    private javax.swing.JComboBox cboxCor;
    private javax.swing.JComboBox cboxEstadoCivil;
    private javax.swing.JComboBox cboxRio;
    private javax.swing.JComboBox cboxSexo;
    private javax.swing.JMenu itmExcluir;
    private javax.swing.JMenu itmSalvar;
    private javax.swing.JMenu itmVoltar;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel lblComunidade;
    private javax.swing.JLabel lblCor;
    private javax.swing.JLabel lblDataNascimento;
    private javax.swing.JLabel lblEstadoCivil;
    private javax.swing.JLabel lblNacionalidade;
    private javax.swing.JLabel lblNaturalidade;
    private javax.swing.JLabel lblNome;
    private javax.swing.JLabel lblProfissao;
    private javax.swing.JLabel lblRio;
    private javax.swing.JLabel lblSexo;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JFormattedTextField txtDataNascimento;
    private javax.swing.JTextField txtNacionalidade;
    private javax.swing.JTextField txtNaturalidade;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtProfissao;
    private javax.swing.JFormattedTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
