package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormReceita;
import br.mackenzie.simacr.interfaces.IMedicamento;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class FormReceita extends javax.swing.JFrame {

    /**
     * Creates new form FormPrescricaoMedica
     */
    DefaultTableModel modelo, modelo2;
    private IControllerFormReceita controller;

    public FormReceita(IControllerFormReceita var) {
        initComponents();
        this.setVisible(true);
        controller = var;
        modelo = (DefaultTableModel) tblPaciente.getModel();
        modelo2 = (DefaultTableModel) tblReceita.getModel();
        tblReceita.removeColumn(tblReceita.getColumnModel().getColumn(0));
        tblPaciente.removeColumn(tblPaciente.getColumnModel().getColumn(0));
        txtPaciente.setText(controller.buscarNomePaciente());
    }

    public ArrayList<String[]> getListaReceita() {
        ArrayList<String[]> retorno = new ArrayList<String[]>();
        int aux;
        for (aux = 0; aux < modelo2.getRowCount(); aux++) {
            retorno.add(new String[]{String.valueOf(modelo2.getValueAt(aux, 0)), String.valueOf(modelo2.getValueAt(aux, 2)), String.valueOf(modelo2.getValueAt(aux, 3))});
        }
        return retorno;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPaciente = new javax.swing.JLabel();
        lblMedicamento = new javax.swing.JLabel();
        txtMedicamento = new javax.swing.JTextField();
        btnPesquisa = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPaciente = new javax.swing.JTable();
        lblReceita = new javax.swing.JLabel();
        btnExcluir = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReceita = new javax.swing.JTable();
        txtPaciente = new javax.swing.JTextField();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCancelar = new javax.swing.JMenu();
        mnuFinalizar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Prescrição Médica");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblPaciente.setText("Nome Paciente:");

        lblMedicamento.setText("Buscar medicamento:");

        btnPesquisa.setText("Pesquisar");
        btnPesquisa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisaActionPerformed(evt);
            }
        });

        tblPaciente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome Comercial", "Principio Ativo", "Laboratório", "Forma Farmaceutica", "Em Estoque"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPaciente.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblPaciente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblPacienteMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblPaciente);
        tblPaciente.getColumnModel().getColumn(0).setResizable(false);

        lblReceita.setText("Receita do Paciente");

        btnExcluir.setText("Excluir Medicamento");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        tblReceita.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Principio Ativo", "Quantidade", "Prescrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblReceita.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        tblReceita.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblReceitaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblReceita);
        tblReceita.getColumnModel().getColumn(0).setResizable(false);
        tblReceita.getColumnModel().getColumn(1).setResizable(false);
        tblReceita.getColumnModel().getColumn(2).setResizable(false);
        tblReceita.getColumnModel().getColumn(3).setResizable(false);

        txtPaciente.setEnabled(false);

        mnuCancelar.setText("Cancelar");
        mnuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCancelarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCancelar);

        mnuFinalizar.setText("Finalizar");
        mnuFinalizar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuFinalizarMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuFinalizar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblReceita)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPaciente)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblMedicamento)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 62, Short.MAX_VALUE)))
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(263, 263, 263)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMedicamento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblMedicamento)
                        .addComponent(btnPesquisa)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblReceita)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 28, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPesquisaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisaActionPerformed
        int aux;
        if (modelo.getRowCount() > 0) {
            for (aux = modelo.getRowCount(); aux > 0; aux--) {
                modelo.removeRow(0);
            }
        }
        for (IMedicamento imed : controller.buscarMedicamentos(txtMedicamento.getText())) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{imed.getId(), imed.getNomeComercial(), imed.getPrincipioAtivo(), imed.getLaboratorio(), imed.getFormaFarmaceutica(), imed.getEmEstoque()});
        }
    }//GEN-LAST:event_btnPesquisaActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        if (tblReceita.getSelectedRow() != -1) {
            modelo2.removeRow(tblReceita.getSelectedRow());
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void mnuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCancelarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_mnuCancelarMouseClicked

    private void mnuFinalizarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuFinalizarMouseClicked
        controller.terminar();
    }//GEN-LAST:event_mnuFinalizarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    private void tblPacienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblPacienteMouseClicked
        if (evt.getClickCount() > 1) {
            JTable target = (JTable) evt.getSource();
            Object idRemedio = (Long) modelo.getValueAt(target.getSelectedRow(), 0);
            int aux;
            for (aux = tblReceita.getRowCount() - 1; aux >= 0; aux--) {
                if (idRemedio == modelo2.getValueAt(aux, 0)) {
                    aux = -2;
                }
            }
            if (aux == -1) {
                try {
                    Integer quantidade = Integer.valueOf(JOptionPane.showInputDialog(this, "Quantidade do remédio"));
                    if (quantidade != null) {
                        if (quantidade > (Integer) modelo.getValueAt(target.getSelectedRow(), 5)) {
                            JOptionPane.showMessageDialog(this, "Quantidade insuficiente no estoque");
                            return;
                        }
                        String prescricao = JOptionPane.showInputDialog(this, "Prescrição do remédio");
                        if (prescricao != null) {
                            modelo2.insertRow(modelo2.getRowCount(), new Object[]{modelo.getValueAt(target.getSelectedRow(), 0), modelo.getValueAt(target.getSelectedRow(), 1), quantidade, prescricao});
                        }
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Informar quantidade em numeros inteiros");
                }
            }
        }
    }//GEN-LAST:event_tblPacienteMouseClicked
    private void tblReceitaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblReceitaMouseClicked
        if (evt.getClickCount() > 1) {
            JTable target = (JTable) evt.getSource();
            modelo2.removeRow(target.getSelectedRow());
        }
    }//GEN-LAST:event_tblReceitaMouseClicked
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnPesquisa;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblMedicamento;
    private javax.swing.JLabel lblPaciente;
    private javax.swing.JLabel lblReceita;
    private javax.swing.JMenu mnuCancelar;
    private javax.swing.JMenu mnuFinalizar;
    private javax.swing.JTable tblPaciente;
    private javax.swing.JTable tblReceita;
    private javax.swing.JTextField txtMedicamento;
    private javax.swing.JTextField txtPaciente;
    // End of variables declaration//GEN-END:variables
}
