/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormCadastrarMedicamentos;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class FormCadastrarMedicamentos extends javax.swing.JFrame {

    IControllerFormCadastrarMedicamentos controller; // Um atributo da classe FormCadastrarMedicamento

    /**
     * Creates new form FormCadastrarMedicamentos
     */
    public FormCadastrarMedicamentos(IControllerFormCadastrarMedicamentos x) {


        initComponents();
        controller = x;
        this.setVisible(true);
        this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeComercila = new javax.swing.JLabel();
        lblPrincipioAtivo = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        lblFormaFarmaceutica = new javax.swing.JLabel();
        txtNomeComercial = new javax.swing.JTextField();
        txtPrincipioAtivo = new javax.swing.JTextField();
        txtLaboratorio = new javax.swing.JTextField();
        txtFormaFarmaceutica = new javax.swing.JTextField();
        menuCadastrarMedicamento = new javax.swing.JMenuBar();
        menuCancelar = new javax.swing.JMenu();
        menuSalvarMedicamento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Cadastro de Medicamento");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNomeComercila.setText("Nome Comercial");

        lblPrincipioAtivo.setText("Princípio Ativo");

        lblLaboratorio.setText("Laboratório");

        lblFormaFarmaceutica.setText("Forma Farmaceutica");

        menuCancelar.setText("Voltar");
        menuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCancelarMouseClicked(evt);
            }
        });
        menuCadastrarMedicamento.add(menuCancelar);

        menuSalvarMedicamento.setText("Salvar");
        menuSalvarMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalvarMedicamentoMouseClicked(evt);
            }
        });
        menuCadastrarMedicamento.add(menuSalvarMedicamento);

        setJMenuBar(menuCadastrarMedicamento);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFormaFarmaceutica))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPrincipioAtivo)
                                    .addComponent(txtPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(lblLaboratorio)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNomeComercila)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtFormaFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeComercila)
                    .addComponent(lblPrincipioAtivo))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaFarmaceutica)
                    .addComponent(lblLaboratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormaFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalvarMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalvarMedicamentoMouseClicked
        if ((txtNomeComercial.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar o nome comercial");
        } else if ((txtPrincipioAtivo.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar o principio ativo");
        } else if ((txtFormaFarmaceutica.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar a forma farmaceutica");
        } else if ((txtLaboratorio.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar o laboratório");
        } else {
            controller.salvarMedicamentos(txtNomeComercial.getText(), txtPrincipioAtivo.getText(), txtFormaFarmaceutica.getText(), txtLaboratorio.getText());
        }
    }//GEN-LAST:event_menuSalvarMedicamentoMouseClicked

    private void menuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCancelarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_menuCancelarMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing
    /**
     * @param args the command line arguments
     */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblFormaFarmaceutica;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblNomeComercila;
    private javax.swing.JLabel lblPrincipioAtivo;
    private javax.swing.JMenuBar menuCadastrarMedicamento;
    private javax.swing.JMenu menuCancelar;
    private javax.swing.JMenu menuSalvarMedicamento;
    private javax.swing.JTextField txtFormaFarmaceutica;
    private javax.swing.JTextField txtLaboratorio;
    private javax.swing.JTextField txtNomeComercial;
    private javax.swing.JTextField txtPrincipioAtivo;
    // End of variables declaration//GEN-END:variables
}
