/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormDadosMedicamento;
import br.mackenzie.simacr.interfaces.ILote;
import br.mackenzie.simacr.interfaces.IMedicamento;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author root
 */
public class FormDadosMedicamento extends javax.swing.JFrame {

    IControllerFormDadosMedicamento controller;
    DefaultTableModel modelo;
    Long idMedicamento;

    /**
     * Creates new form FormCadastrarMedicamentos
     */
    public FormDadosMedicamento(IControllerFormDadosMedicamento varController, IMedicamento varMedicamento) {
        initComponents();
        controller = varController;
        idMedicamento = varMedicamento.getId();
        txtFormaFarmaceutica.setText(varMedicamento.getFormaFarmaceutica());
        txtLaboratorio.setText(varMedicamento.getLaboratorio());
        txtNomeComercial.setText(varMedicamento.getNomeComercial());
        txtPrincipioAtivo.setText(varMedicamento.getPrincipioAtivo());
        initTable();
        popularTabela();
        updateQtde(varMedicamento);

        this.setVisible(true);
        this.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNomeComercila = new javax.swing.JLabel();
        lblPrincipioAtivo = new javax.swing.JLabel();
        lblLaboratorio = new javax.swing.JLabel();
        lblFormaFarmaceutica = new javax.swing.JLabel();
        lblemEstoque = new javax.swing.JLabel();
        txtNomeComercial = new javax.swing.JTextField();
        txtPrincipioAtivo = new javax.swing.JTextField();
        txtLaboratorio = new javax.swing.JTextField();
        txtQuantidade = new javax.swing.JTextField();
        txtFormaFarmaceutica = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblLotes = new javax.swing.JTable();
        lblReserva = new javax.swing.JLabel();
        txtReserva = new javax.swing.JTextField();
        btnNovoLote = new javax.swing.JButton();
        btnExcluirLote = new javax.swing.JButton();
        menuBase = new javax.swing.JMenuBar();
        menuCancelar = new javax.swing.JMenu();
        menuExcluirMedicamento = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Dados de Medicamento");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNomeComercila.setText("Nome Comercial");

        lblPrincipioAtivo.setText("Princípio Ativo");

        lblLaboratorio.setText("Laboratório");

        lblFormaFarmaceutica.setText("Forma Farmaceutica");

        lblemEstoque.setText("Quantidade Em Estoque");

        txtNomeComercial.setEnabled(false);

        txtPrincipioAtivo.setEnabled(false);

        txtLaboratorio.setEnabled(false);

        txtQuantidade.setEnabled(false);

        txtFormaFarmaceutica.setEnabled(false);

        tblLotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num. Lote", "Validade", "Unidades", "Aquisição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblLotes);

        lblReserva.setText("Quantidade Em Reserva");

        txtReserva.setEnabled(false);

        btnNovoLote.setText("Novo Lote");
        btnNovoLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoLoteActionPerformed(evt);
            }
        });

        btnExcluirLote.setText("Excluir Lote");
        btnExcluirLote.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirLoteActionPerformed(evt);
            }
        });

        menuCancelar.setText("Voltar");
        menuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCancelarMouseClicked(evt);
            }
        });
        menuBase.add(menuCancelar);

        menuExcluirMedicamento.setText("Excluir Medicamento");
        menuExcluirMedicamento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuExcluirMedicamentoMouseClicked(evt);
            }
        });
        menuBase.add(menuExcluirMedicamento);

        setJMenuBar(menuBase);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFormaFarmaceutica)
                            .addComponent(lblNomeComercila)
                            .addComponent(txtNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblPrincipioAtivo)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtPrincipioAtivo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(lblLaboratorio)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 317, Short.MAX_VALUE)
                        .addComponent(btnExcluirLote)
                        .addGap(18, 18, 18)
                        .addComponent(btnNovoLote))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(txtQuantidade, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtFormaFarmaceutica, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 243, Short.MAX_VALUE))
                            .addComponent(lblemEstoque))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblReserva)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txtLaboratorio)
                            .addComponent(txtReserva))))
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNomeComercila)
                    .addComponent(lblPrincipioAtivo))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeComercial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPrincipioAtivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFormaFarmaceutica)
                    .addComponent(lblLaboratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFormaFarmaceutica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLaboratorio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblemEstoque)
                    .addComponent(lblReserva))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtReserva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoLote)
                    .addComponent(btnExcluirLote))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCancelarMouseClicked
        controller.cancelar();
    }//GEN-LAST:event_menuCancelarMouseClicked

    private void menuExcluirMedicamentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuExcluirMedicamentoMouseClicked
        controller.excluirMedicamento(idMedicamento);
    }//GEN-LAST:event_menuExcluirMedicamentoMouseClicked

    private void btnNovoLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoLoteActionPerformed
        controller.abrirFormCadastrarLote();
    }//GEN-LAST:event_btnNovoLoteActionPerformed

    private void btnExcluirLoteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirLoteActionPerformed
        if (tblLotes.getSelectedRow() != -1) {
            controller.excluirLote(idMedicamento, (String) tblLotes.getValueAt(tblLotes.getSelectedRow(), 0));
        }
    }//GEN-LAST:event_btnExcluirLoteActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

    public void updateQtde(IMedicamento imed) {
        txtQuantidade.setText(String.valueOf(imed.getEmEstoque()));
        txtReserva.setText(String.valueOf(imed.getEmReserva()));
    }

    public void popularTabela() {
        initTable();
        for (ILote lote : controller.getLotes(idMedicamento)) {
            modelo.insertRow(modelo.getRowCount(), new Object[]{lote.getNumeroLote(), lote.getValidade(), lote.getUnidades(), lote.getAdquirido()});
        }


    }

    private void initTable() {
        modelo = (DefaultTableModel) tblLotes.getModel();
        modelo.setDataVector(new Object[][]{}, new Object[]{"Num. Lote", "Validade", "Unidades", "Aquisição"});
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnExcluirLote;
    private javax.swing.JButton btnNovoLote;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFormaFarmaceutica;
    private javax.swing.JLabel lblLaboratorio;
    private javax.swing.JLabel lblNomeComercila;
    private javax.swing.JLabel lblPrincipioAtivo;
    private javax.swing.JLabel lblReserva;
    private javax.swing.JLabel lblemEstoque;
    private javax.swing.JMenuBar menuBase;
    private javax.swing.JMenu menuCancelar;
    private javax.swing.JMenu menuExcluirMedicamento;
    private javax.swing.JTable tblLotes;
    private javax.swing.JTextField txtFormaFarmaceutica;
    private javax.swing.JTextField txtLaboratorio;
    private javax.swing.JTextField txtNomeComercial;
    private javax.swing.JTextField txtPrincipioAtivo;
    private javax.swing.JTextField txtQuantidade;
    private javax.swing.JTextField txtReserva;
    // End of variables declaration//GEN-END:variables
}
