/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package br.mackenzie.simacr.views;

import br.mackenzie.simacr.controllers.interfaces.IControllerFormCadastrarLote;
import javax.swing.JOptionPane;

/**
 *
 * @author root
 */
public class FormCadastrarLote extends javax.swing.JFrame {

    IControllerFormCadastrarLote controller;

    /**
     * Creates new form FormCadastrarLote
     */
    public FormCadastrarLote(IControllerFormCadastrarLote var) {
        initComponents();
        controller = var;
        cboxAdquirido.removeAllItems();
        cboxAdquirido.addItem("");
        cboxAdquirido.addItem("Comprado");
        cboxAdquirido.addItem("Doado");   
        lblDoado.setVisible(false);
        txtDoado.setVisible(false);
        this.setVisible(true);
        this.requestFocus();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpCadastrarLote = new javax.swing.JPanel();
        lblNumLote = new javax.swing.JLabel();
        lblValidade = new javax.swing.JLabel();
        lblNumUnidade = new javax.swing.JLabel();
        txtNumLote = new javax.swing.JTextField();
        txtNumUnidades = new javax.swing.JTextField();
        txtValidade = new javax.swing.JFormattedTextField();
        cboxAdquirido = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        lblDoado = new javax.swing.JLabel();
        txtDoado = new javax.swing.JTextField();
        menuOpcoes = new javax.swing.JMenuBar();
        menuCancelar = new javax.swing.JMenu();
        menuSalvar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Simacr 2.0 - Cadastro de Lotes");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        lblNumLote.setText("Número do Lote");

        lblValidade.setText("Validade");

        lblNumUnidade.setText("Número de Unidades");

        try {
            txtValidade.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        javax.swing.GroupLayout jpCadastrarLoteLayout = new javax.swing.GroupLayout(jpCadastrarLote);
        jpCadastrarLote.setLayout(jpCadastrarLoteLayout);
        jpCadastrarLoteLayout.setHorizontalGroup(
            jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLoteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumUnidade)
                    .addComponent(lblNumLote)
                    .addComponent(lblValidade))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtValidade)
                    .addComponent(txtNumLote)
                    .addComponent(txtNumUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );
        jpCadastrarLoteLayout.setVerticalGroup(
            jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCadastrarLoteLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumLote)
                    .addComponent(txtNumLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblValidade)
                    .addComponent(txtValidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpCadastrarLoteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumUnidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumUnidade))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        cboxAdquirido.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboxAdquiridoItemStateChanged(evt);
            }
        });

        jLabel1.setText("Aquisição via:");

        lblDoado.setText("por:");

        menuCancelar.setText("Voltar");
        menuCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuCancelarMouseClicked(evt);
            }
        });
        menuOpcoes.add(menuCancelar);

        menuSalvar.setText("Salvar");
        menuSalvar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuSalvarMouseClicked(evt);
            }
        });
        menuOpcoes.add(menuSalvar);

        setJMenuBar(menuOpcoes);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpCadastrarLote, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblDoado)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDoado))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboxAdquirido, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpCadastrarLote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(cboxAdquirido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoado)
                    .addComponent(txtDoado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuSalvarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuSalvarMouseClicked
        if ((txtNumLote.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar o numero do lote");
            return;
        } else if ((txtValidade.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar a validade");
            return;
        } else if ((txtNumUnidades.getText().trim().equals(""))) {
            JOptionPane.showMessageDialog(this, "Informar o numero de unidades");
            return;
        } else {
            try {
                Integer.parseInt(txtNumUnidades.getText());
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(this, "Insira numeros inteiros válidos na quantidade");
                return;
            }
        }
        String adquiridoPor = "";
        if(cboxAdquirido.getSelectedIndex()<1){
            JOptionPane.showMessageDialog(this, "Informar o tipo de aquisição");
            return;
        }else if(cboxAdquirido.getSelectedIndex()==2)
            adquiridoPor = String.valueOf("Doado por - " + txtDoado.getText());
        else
            adquiridoPor = "Compra";
        controller.salvarLote(txtNumLote.getText(), txtValidade.getText(), Integer.parseInt(txtNumUnidades.getText()),adquiridoPor);
    }//GEN-LAST:event_menuSalvarMouseClicked

    private void menuCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuCancelarMouseClicked
        // TODO add your handling code here:
        controller.cancelar();
    }//GEN-LAST:event_menuCancelarMouseClicked

    private void cboxAdquiridoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboxAdquiridoItemStateChanged
        if(cboxAdquirido.getSelectedIndex()==2)
        {
            lblDoado.setVisible(true);
            txtDoado.setVisible(true);
        }
        else
        {
            lblDoado.setVisible(false);
            txtDoado.setVisible(false);
        }
    }//GEN-LAST:event_cboxAdquiridoItemStateChanged

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        controller.cancelar();
    }//GEN-LAST:event_formWindowClosing

        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboxAdquirido;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jpCadastrarLote;
    private javax.swing.JLabel lblDoado;
    private javax.swing.JLabel lblNumLote;
    private javax.swing.JLabel lblNumUnidade;
    private javax.swing.JLabel lblValidade;
    private javax.swing.JMenu menuCancelar;
    private javax.swing.JMenuBar menuOpcoes;
    private javax.swing.JMenu menuSalvar;
    private javax.swing.JTextField txtDoado;
    private javax.swing.JTextField txtNumLote;
    private javax.swing.JTextField txtNumUnidades;
    private javax.swing.JFormattedTextField txtValidade;
    // End of variables declaration//GEN-END:variables
}
